// <auto-generated />
using System;
using Blog.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Blog.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20200722081639_SeedPosts")]
    partial class SeedPosts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Blog.Models.Posts", b =>
                {
                    b.Property<string>("BlogSlug")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Body");

                    b.Property<DateTime>("CreatedAtDate");

                    b.Property<string>("Description");

                    b.Property<int>("TagsId");

                    b.Property<string>("Title");

                    b.Property<DateTime>("UpdatedAtDate");

                    b.HasKey("BlogSlug");

                    b.HasIndex("TagsId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            BlogSlug = "augmented-reality-ios-application",
                            Body = "The app is simple to use, and will help you decide on your best furniture fit.",
                            CreatedAtDate = new DateTime(2020, 7, 22, 10, 16, 39, 35, DateTimeKind.Local).AddTicks(3228),
                            Description = "Rubicon Software Development and Gazzda furniture are proud to launch an augmented reality app.",
                            TagsId = 1,
                            Title = "Augmented Reality iOS Application",
                            UpdatedAtDate = new DateTime(2020, 7, 22, 10, 16, 39, 41, DateTimeKind.Local).AddTicks(2130)
                        });
                });

            modelBuilder.Entity("Blog.Models.Tags", b =>
                {
                    b.Property<int>("TagsId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AllowedBarsList");

                    b.HasKey("TagsId");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            TagsId = 1,
                            AllowedBarsList = "iOS, AR"
                        },
                        new
                        {
                            TagsId = 2,
                            AllowedBarsList = "iOS, AR, Gazzda"
                        },
                        new
                        {
                            TagsId = 3,
                            AllowedBarsList = "trends, innovation, 2018"
                        });
                });

            modelBuilder.Entity("Blog.Models.Posts", b =>
                {
                    b.HasOne("Blog.Models.Tags", "Tags")
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
