// <auto-generated />
using System;
using Blog.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Blog.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20200722090241_SeedPostsgain")]
    partial class SeedPostsgain
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Blog.Models.Posts", b =>
                {
                    b.Property<string>("BlogSlug")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Body");

                    b.Property<DateTime>("CreatedAtDate");

                    b.Property<string>("Description");

                    b.Property<int>("TagsId");

                    b.Property<string>("Title");

                    b.Property<DateTime>("UpdatedAtDate");

                    b.HasKey("BlogSlug");

                    b.HasIndex("TagsId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            BlogSlug = "augmented-reality-ios-application",
                            Body = "The app is simple to use, and will help you decide on your best furniture fit.",
                            CreatedAtDate = new DateTime(2020, 7, 22, 11, 2, 41, 404, DateTimeKind.Local).AddTicks(5545),
                            Description = "Rubicon Software Development and Gazzda furniture are proud to launch an augmented reality app.",
                            TagsId = 1,
                            Title = "Augmented Reality iOS Application",
                            UpdatedAtDate = new DateTime(2020, 7, 22, 11, 2, 41, 409, DateTimeKind.Local).AddTicks(2400)
                        },
                        new
                        {
                            BlogSlug = "trends-slug",
                            Body = "An opinionated commentary, of the most important presentation of the year",
                            CreatedAtDate = new DateTime(2020, 7, 22, 11, 2, 41, 409, DateTimeKind.Local).AddTicks(5210),
                            Description = "Ever wonder how?",
                            TagsId = 3,
                            Title = "Internet Trends 2018",
                            UpdatedAtDate = new DateTime(2020, 7, 22, 11, 2, 41, 409, DateTimeKind.Local).AddTicks(5239)
                        },
                        new
                        {
                            BlogSlug = "augmented-reality-ios-application-2",
                            Body = "The app is simple to use, and will help you decide on your best furniture fit.",
                            CreatedAtDate = new DateTime(2020, 7, 22, 11, 2, 41, 409, DateTimeKind.Local).AddTicks(5259),
                            Description = "Rubicon Software Development and Gazzda furniture are proud to launch an augmented reality app.",
                            TagsId = 2,
                            Title = "Augmented Reality iOS Application 2",
                            UpdatedAtDate = new DateTime(2020, 7, 22, 11, 2, 41, 409, DateTimeKind.Local).AddTicks(5264)
                        },
                        new
                        {
                            BlogSlug = "augmented-reality-ios-application-3",
                            Body = "The app is simple to use, and will help you decide on your best furniture fit.",
                            CreatedAtDate = new DateTime(2020, 7, 22, 11, 2, 41, 409, DateTimeKind.Local).AddTicks(5273),
                            Description = "Rubicon Software Development and Gazzda furniture are proud to launch an augmented reality app.",
                            TagsId = 1,
                            Title = "Augmented Reality iOS Application 3",
                            UpdatedAtDate = new DateTime(2020, 7, 22, 11, 2, 41, 409, DateTimeKind.Local).AddTicks(5278)
                        });
                });

            modelBuilder.Entity("Blog.Models.Tags", b =>
                {
                    b.Property<int>("TagsId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AllowedBarsList");

                    b.HasKey("TagsId");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            TagsId = 1,
                            AllowedBarsList = "iOS,AR"
                        },
                        new
                        {
                            TagsId = 2,
                            AllowedBarsList = "iOS,AR,Gazzda"
                        },
                        new
                        {
                            TagsId = 3,
                            AllowedBarsList = "trends,innovation,2018"
                        });
                });

            modelBuilder.Entity("Blog.Models.Posts", b =>
                {
                    b.HasOne("Blog.Models.Tags", "Tags")
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
